/**
 * MitigationPlan Model
 * Stores AI-generated (or rule-based fallback) personalized action plans
 * One plan covers a 7-day period
 */
const mongoose = require('mongoose');

const MitigationPlanSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User ID is required']
    },

    /**
     * Month window this plan covers
     */
    periodStart: {
      type: String, // YYYY-MM-DD
      required: [true, 'Period start is required']
    },
    periodEnd: {
      type: String, // YYYY-MM-DD
      required: [true, 'Period end is required']
    },

    /**
     * Total emissions during the period (baseline for recommendations)
     */
    baseEmissionKg: {
      type: Number,
      required: true,
      default: 0
    },

    /**
     * Status of the plan
     * - pending: waiting to be generated
     * - generated: successfully generated
     * - failed: generation failed (should have fallback active)
     */
    status: {
      type: String,
      enum: ['pending', 'generated', 'failed'],
      default: 'pending'
    },

    /**
     * Type of plan
     * - GENERAL_PLAN: generic recommendations for new users (<30 logs)
     * - MONTHLY_PLAN: AI-generated personalized recommendations (30+ logs)
     */
    type: {
      type: String,
      enum: ['GENERAL_PLAN', 'MONTHLY_PLAN'],
      default: 'GENERAL_PLAN'
    },

    /**
     * Which provider generated this plan
     * - external-ai: generated by external AI service
     * - fallback-rule-based: generated by rule-based fallback
     */
    source: {
      type: String,
      enum: ['external-ai', 'fallback-rule-based'],
      required: [true, 'Source is required']
    },

    /**
     * Array of personalized recommendations
     */
    recommendations: [
      {
        /**
         * Short title of the recommendation
         */
        text: {
          type: String,
          required: true
        },

        /**
         * Detailed description of the action
         */
        description: {
          type: String,
          default: ''
        },

        /**
         * Estimated CO2 reduction in kg if the student takes this action
         */
        estimatedReductionKg: {
          type: Number,
          required: true,
          min: [0, 'Reduction cannot be negative']
        },

        /**
         * Effort level required: 'low', 'medium', 'high'
         */
        effortLevel: {
          type: String,
          enum: ['low', 'medium', 'high'],
          default: 'medium'
        },

        /**
         * Category of recommendation for filtering/display
         */
        category: {
          type: String,
          enum: ['transportation', 'food', 'waste', 'energy', 'general'],
          default: 'general'
        },

        /**
         * Additional context (e.g., "based on your 8+ non-veg meals last month")
         */
        context: {
          type: String,
          default: null
        }
      }
    ],

    /**
     * When this plan was generated
     */
    generatedAt: {
      type: Date,
      default: Date.now
    },

    /**
     * Whether this plan is currently active
     */
    isActive: {
      type: Boolean,
      default: true
    }
  },
  { timestamps: true }
);

/**
 * Index for finding active plans for a user
 */
MitigationPlanSchema.index({ userId: 1, isActive: 1 });

module.exports = mongoose.model('MitigationPlan', MitigationPlanSchema);
