import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'en' | 'ne';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    title: '', // Title replaced by image in UI
    subtitle: 'School Carbon Footprint Action System',
    tagline: 'Measure. Reduce. Grow.',
    school_admin: 'School Admin',
    student: 'Student',
    login: 'Login',
    logout: 'Logout',
    signed_in_as: 'Signed in as',
    current_school: 'Current School',
    dashboard: 'Dashboard',
    data_entry: 'Data Entry',
    carbon_report: 'Carbon Report',
    action_plan: 'Action Plan',
    support: 'Support',
    leaderboard: 'Leaderboard',
    impact_ledger: 'Impact Ledger',
    verification: 'Verification',
    registration: 'School Registration',
    step: 'Step',
    of: 'of',
    next: 'Next',
    back: 'Back',
    submit: 'Submit',
    school_name: 'School Name',
    district: 'District',
    province: 'Province',
    students_count: 'Number of Students',
    teachers_count: 'Number of Teachers',
    electricity_source: 'Electricity Source',
    cooking_fuel: 'Cooking Fuel',
    transport: 'Transport (Majority)',
    grid: 'Grid',
    generator: 'Generator',
    solar: 'Solar',
    none: 'None',
    wood: 'Wood',
    lpg: 'LPG',
    kerosene: 'Kerosene',
    walking: 'Walking',
    school_bus: 'School Bus',
    public_transport: 'Public Transport',
    mixed: 'Mixed',
    archetype: 'School Archetype',
    remote: 'Remote',
    semi_urban: 'Semi-Urban',
    urban: 'Urban',
    monthly_footprint: 'This Month\'s Carbon Footprint',
    kg_co2: 'kg CO₂',
    energy_co2: 'Energy CO₂',
    transport_co2: 'Transport CO₂',
    waste_co2: 'Waste CO₂',
    trees_needed: 'trees needed to absorb this',
    enter_monthly_data: 'Enter Monthly Data',
    progress_to_goal: 'Progress to Goal',
    recent_activities: 'Recent Activities',
    electricity_bill: 'Electricity Bill Amount (NPR)',
    diesel_liters: 'Diesel Used (Liters)',
    cooking_amount: 'Cooking Fuel Amount (kg)',
    waste_bags: 'Waste Bags per Week',
    upload_bill: 'Upload Electricity Bill Photo',
    calculate_carbon: 'Calculate My Carbon',
    how_came_school: 'How did you come to school today?',
    brought_plastic: 'Did you bring single-use plastic?',
    wasted_food: 'Did you waste food today?',
    yes: 'Yes',
    no: 'No',
    submit_week: 'Submit This Week',
    streak: 'You have submitted',
    weeks_row: 'weeks in a row!',
    total_co2: 'Total CO₂',
    biggest_issue: 'Your biggest issue',
    emotional_impact: 'Emotional Impact',
    before_after: 'Before vs After',
    actions_for_school: 'Actions for Your School',
    all: 'All',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    expected_saved: 'Expected CO₂ Saved',
    cost: 'Cost',
    difficulty: 'Difficulty',
    see_details: 'See Details',
    month: 'Month',
    week: 'Week',
    upload_proof: 'Upload Proof',
    completed: 'Completed',
    upcoming: 'Upcoming',
    total_reduced: 'Total CO₂ Reduced by All Schools',
    active_schools: 'Active Schools',
    actions_taken: 'Actions Taken',
    resources_received: 'Resources Received',
    supported_by: 'Supported By',
    fund_pool: 'Pool Available',
    contributed_by: 'Contributed by',
    support_available: 'Support Available for Your School',
    impact_points: 'Impact Points',
    tier: 'Tier',
    unlocked: 'Unlocked',
    locked: 'Locked',
    available_orgs: 'Available Support Organizations',
    mentor_commitment: 'To receive support, commit to mentoring 1 nearby school',
    my_province: 'My Province',
    my_archetype: 'My Archetype',
    all_nepal: 'All Nepal',
    rank: 'Rank',
    improvement: 'Improvement',
    badge: 'Badge',
    fair_note: 'Schools compared within same archetype only — fair for all',
    verify_reduction: 'Verify Your Reduction',
    upload_before_after: 'Upload Bills (Before & After)',
    upload_action_proof: 'Upload Action Proof Photos',
    admin_confirmation: 'Admin/Teacher Confirmation',
    submit_verification: 'Submit for Verification',
    under_review: 'Under Review',
    verified: 'Verified',
    complete: 'Complete',
    in_progress: 'In Progress',
    pending: 'Pending',
  },
  ne: {
    title: 'हरित पाठशाला',
    subtitle: 'विद्यालय कार्बन पदचिह्न कार्य प्रणाली',
    tagline: 'मापन गर्नुहोस्। घटाउनुहोस्। बढाउनुहोस्।',
    school_admin: 'विद्यालय प्रशासक',
    student: 'विद्यार्थी',
    login: 'लगइन',
    logout: 'लगआउट',
    signed_in_as: 'लगइन गरिएको',
    current_school: 'हालको विद्यालय',
    dashboard: 'ड्यासबोर्ड',
    data_entry: 'डाटा प्रविष्टि',
    carbon_report: 'कार्बन रिपोर्ट',
    action_plan: 'कार्य योजना',
    support: 'सहयोग',
    leaderboard: 'लिडरबोर्ड',
    impact_ledger: 'प्रभाव खाता',
    verification: 'प्रमाणीकरण',
    registration: 'विद्यालय दर्ता',
    step: 'चरण',
    of: 'को',
    next: 'अर्को',
    back: 'पछाडि',
    submit: 'पेश गर्नुहोस्',
    school_name: 'विद्यालयको नाम',
    district: 'जिल्ला',
    province: 'प्रदेश',
    students_count: 'विद्यार्थी संख्या',
    teachers_count: 'शिक्षक संख्या',
    electricity_source: 'बिजुलीको स्रोत',
    cooking_fuel: 'खाना पकाउने इन्धन',
    transport: 'यातायात (बहुमत)',
    grid: 'ग्रिड',
    generator: 'जेनेरेटर',
    solar: 'सौर्य',
    none: 'कुनै पनि छैन',
    wood: 'दाउरा',
    lpg: 'एलपीजी',
    kerosene: 'मट्टीतेल',
    walking: 'हिँडेर',
    school_bus: 'विद्यालय बस',
    public_transport: 'सार्वजनिक यातायात',
    mixed: 'मिश्रित',
    archetype: 'विद्यालय प्रकार',
    remote: 'दुर्गम',
    semi_urban: 'अर्ध-सहरी',
    urban: 'सहरी',
    monthly_footprint: 'यस महिनाको कार्बन पदचिह्न',
    kg_co2: 'किलोग्राम CO₂',
    energy_co2: 'ऊर्जा CO₂',
    transport_co2: 'यातायात CO₂',
    waste_co2: 'फोहोर CO₂',
    trees_needed: 'रूखहरू यो अवशोषित गर्न आवश्यक',
    enter_monthly_data: 'मासिक डाटा प्रविष्ट गर्नुहोस्',
    progress_to_goal: 'लक्ष्य तिर प्रगति',
    recent_activities: 'हालैका गतिविधिहरू',
    electricity_bill: 'बिजुलीको बिल रकम (रु.)',
    diesel_liters: 'डिजेल प्रयोग (लिटर)',
    cooking_amount: 'खाना पकाउने इन्धन मात्रा (किलो)',
    waste_bags: 'प्रति हप्ता फोहोर झोला',
    upload_bill: 'बिजुलीको बिल फोटो अपलोड गर्नुहोस्',
    calculate_carbon: 'मेरो कार्बन गणना गर्नुहोस्',
    how_came_school: 'तपाईं आज विद्यालय कसरी आउनुभयो?',
    brought_plastic: 'के तपाईंले एक पटक प्रयोग हुने प्लास्टिक ल्याउनुभयो?',
    wasted_food: 'के तपाईंले आज खाना बर्बाद गर्नुभयो?',
    yes: 'हो',
    no: 'होइन',
    submit_week: 'यो हप्ता पेश गर्नुहोस्',
    streak: 'तपाईंले पेश गर्नुभएको छ',
    weeks_row: 'हप्ता लगातार!',
    total_co2: 'कुल CO₂',
    biggest_issue: 'तपाईंको सबैभन्दा ठूलो समस्या',
    emotional_impact: 'भावनात्मक प्रभाव',
    before_after: 'पहिले बनाम पछि',
    actions_for_school: 'तपाईंको विद्यालयका लागि कार्यहरू',
    all: 'सबै',
    easy: 'सजिलो',
    medium: 'मध्यम',
    hard: 'कठिन',
    expected_saved: 'अपेक्षित CO₂ बचत',
    cost: 'लागत',
    difficulty: 'कठिनाई',
    see_details: 'विवरण हेर्नुहोस्',
    month: 'महिना',
    week: 'हप्ता',
    upload_proof: 'प्रमाण अपलोड',
    completed: 'पूर्ण',
    upcoming: 'आगामी',
    total_reduced: 'सबै विद्यालयहरूले घटाएको कुल CO₂',
    active_schools: 'सक्रिय विद्यालयहरू',
    actions_taken: 'गरिएका कार्यहरू',
    resources_received: 'प्राप्त स्रोतहरू',
    supported_by: 'द्वारा समर्थित',
    fund_pool: 'उपलब्ध रकम',
    contributed_by: 'योगदान',
    support_available: 'तपाईंको विद्यालयका लागि उपलब्ध सहयोग',
    impact_points: 'प्रभाव अंक',
    tier: 'स्तर',
    unlocked: 'अनलक',
    locked: 'बन्द',
    available_orgs: 'उपलब्ध सहयोग संस्थाहरू',
    mentor_commitment: 'सहयोग प्राप्त गर्न, नजिकको १ विद्यालयलाई सल्लाह दिन प्रतिबद्ध हुनुहोस्',
    my_province: 'मेरो प्रदेश',
    my_archetype: 'मेरो प्रकार',
    all_nepal: 'सम्पूर्ण नेपाल',
    rank: 'स्थान',
    improvement: 'सुधार',
    badge: 'ब्याज',
    fair_note: 'विद्यालयहरू समान प्रकार भित्र मात्र तुलना - सबैका लागि उचित',
    verify_reduction: 'आफ्नो कमी प्रमाणित गर्नुहोस्',
    upload_before_after: 'बिल अपलोड (पहिले र पछि)',
    upload_action_proof: 'कार्य प्रमाण फोटो अपलोड',
    admin_confirmation: 'प्रशासक/शिक्षक पुष्टि',
    submit_verification: 'प्रमाणीकरणका लागि पेश गर्नुहोस्',
    under_review: 'समीक्षाधीन',
    verified: 'प्रमाणित',
    complete: 'पूर्ण',
    in_progress: 'जारी',
    pending: 'बाँकी',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ne' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
